config progress but now getting cursed error
OpenJDK 64-Bit Server VM warning: Option AllowRedefinitionToAddDeleteMethods was deprecated in version 13.0 and will likely be removed in a future release.
Connected to the target VM, address: '127.0.0.1:65408', transport: 'socket'
Error: Unable to initialize main class cpw.mods.bootstraplauncher.BootstrapLauncher in module cpw.mods.bootstraplauncher
Caused by: java.lang.VerifyError: Catch type is not a subclass of Throwable in exception handler 47
Exception Details:
  Location:
    cpw/mods/bootstraplauncher/BootstrapLauncher.loadLegacyClassPath()Ljava/util/List; @47: astore_2
  Reason:
    Type 'java/io/IOException' (constant pool 328) is not assignable to 'java/lang/Throwable'
  Bytecode:
    0000000: 1301 3cb8 012c 4b2a c600 372a 03bd 0016
    0000010: b800 4e4c 2b03 bd00 76b8 013e 9900 232b
    0000020: 03bd 0076 b801 4199 0018 2bb8 0144 b04d
    0000030: bb01 4a59 2aba 014c 0000 2cb7 014d bf12
    0000040: 0d13 0150 b801 2cb8 0025 4c2b 1301 52b8
    0000050: 0154 572b b601 5a9a 0007 b801 5eb0 2bb2
    0000060: 000f b600 2ab8 0160 b0
  Exception Handler Table:
    bci [42, 46] => handler: 47
  Stackmap Table:
    full_frame(@47,{Object[#22],Object[#85]},{Object[#328]})
    chop_frame(@63,1)
    append_frame(@94,Object[#22])

Disconnected from the target VM, address: '127.0.0.1:65408', transport: 'socket'

Process finished with exit code 1